[package]
name = "ScrollableTable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.19.0", default-features = false, features = ['termion'] }
termion = "1.5"